### ISSUE TITLE
Clarify 'any arbitrary method' in TimedAspect documentation

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer-docs#103]
I have been trying with SpringBoot (and associated) 2.1.8.RELEASE and 2.1.5.RELEASE, micrometer (and co) on 1.1.4, 1.1.6 and 1.3.0, Java 11, Java 12 and no joy. 

I have learned that it works for some people and not for some other people. Any ideas here?

EDIT: 

Seemingly it works if you call a @Timed method in a _@Component_ from another _@Component_

Is this how it is supposed to work? The documentation still says that it is supported on _arbitrary_ methods with the TimedAspect but seemingly that does not work.

_Originally posted by @Sampo123 in https://github.com/micrometer-metrics/micrometer/issues/351#issuecomment-543043344_

**Comment by shakuzen** [comment]
The method needs to be called through the AspectJ proxy of the instance. This should be more explicit in the documentation to reduce confusion of users. How proxying is configured can probably be left out as something for Spring/AspectJ's documentation.

**Comment by izeye** [comment]
@shakuzen I created https://github.com/micrometer-metrics/micrometer-docs/pull/106 to try to resolve this.
