### ISSUE TITLE
Update gauge example in documentation

### ISSUE THREAD

**Issue by zeelshah90** [micrometer-metrics/micrometer-docs#107]
In this doc[1] section 9.1 please change the example from

```java
AtomicInteger n = registry.gauge("numberGauge", new AtomicInteger(0));
n.set(1);
n.set(2);
```

TO
```java
AtomicInteger atomicInteger = new AtomicInteger(0);
AtomicInteger n = registry.gauge("numberGauge", atomicInteger);
n.set(1);
n.set(2);
```

As above example does not work due to weakreference of new AtomicIntger(0).
[1] https://micrometer.io/docs/concepts#_gauges

**Comment by izeye** [comment]
@zeelshah90 The example you mentioned seems to be valid for me if you retain any reference to `n`. Am I missing something?

**Comment by shakuzen** [comment]
I have updated the example code with comments that hopefully clarify things. Let me know if anyone thinks further clarification is still necessary.
