### ISSUE TITLE
Missing section for New Relic

### ISSUE THREAD

**Issue by snicoll** [micrometer-metrics/micrometer-docs#14]
I would expect http://micrometer.io/docs/registry/newrelic to give me some information about the support in Micrometer. I am using a pattern in the Spring Boot documentation and the lack of a dedicated section on New Relic is annoying.

Can you please add some doc about that support?

**Comment by jkschneider** [comment]
Added in c338452. Note that the URL is: http://micrometer.io/docs/registry/new-relic (hyphenated name)

**Comment by snicoll** [comment]
Cheers Jon, polished in https://github.com/spring-projects/spring-boot/commit/cb96bbd9be40bffc66d1bd065557a8627bd16817
