### ISSUE TITLE
Documentation website cannot be load.

### ISSUE THREAD

**Issue by Patouche** [micrometer-metrics/micrometer-docs#155]
Hello !!

On firefox (version 86.1), I cannot load the website https://micrometer.io/

It told me the following javascript error : 

![Screenshot_2021-03-24_16-47-35](https://user-images.githubusercontent.com/339955/112340325-b8fb0480-8cc0-11eb-8a2e-85fa1a8f85b5.png)

When I retrieve the html returned from the root page, I got the following content :

```html
<!doctype html><html lang="en">
<head>
<!-- ... -->
    <script>!function(e){function r(r){for(var n,i,l=r[0],c=r[1],f=r[2],p=0,s=[];p<l.length
        ;p++)i=l[p],Object.prototype.hasOwnProperty.call(o,i)&&o[i]&&s.push(o[i][0]),o[i]=0;for(n in
        c)Object.prototype.hasOwnProperty.call(c,n)&&(e[n]=c[n]);for(a&&a(r);s.length;)s.shift()();return
        u.push.apply(u,f||[]),t()}function t(){for(var e,r=0;r<u.length;r++){for(var t=u[r],n=!0,l=1;l<t.length;l++){var
        c=t[l];0!==o[c]&&(n=!1)}n&&(u.splice(r--,1),e=i(i.s=t[0]))}return e}var n={},o={1:0},u=[];function
        i(r){if(n[r])return n[r].exports;var t=n[r]={i:r,l:!1,exports:{}};return
        e[r].call(t.exports,t,t.exports,i),t.l=!0,t.exports}i.m=e,i.c=n,i.d=function(e,r,t){i.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:t})},i.r=function(e){"undefined"!=typeof
        Symbol&&Symbol.toStringTag&&
        Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},i.t=function(e,r){if(1
        &r&&(e=i(e)),8&r)return e;if(4&r&&"object"==typeof e&&e&&e.__esModule)return e;var
        t=Object.create(null);if(i.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:e}),2&r&&"string"!=typeof
        e)for(var n in e)i.d(t,n,function(r){return e[r]}.bind(null,n));return t},i.n=function(e){var r=e&&
        e.__esModule?function(){return e.default}:function(){return e};return i.d(r,"a",r),r},i.o=function(e,r){return
        Object.prototype.hasOwnProperty.call(e,r)},i.p="/";var
        l=this["webpackJsonpmicrometer-docs"]=this["webpackJsonpmicrometer-docs"]||[],c=l.push.bind(l);l.push=r,l=l.slice();for(var
        f=0;f<l.length;f++)r(l[f]);var a=c;t()}([])
    </script>
<!-- ... -->
</body>
</html>
```

Between this `script` tag, we have some `<l.length` that cannot be properly interpreted by Firefox (and maybe other browser as it don't seem to be a valid html).

Maybe, it should be a good idea to have a `CDATA` section if it's possible to wrap the script here.

**Comment by jonatan-ivanov** [comment]
@Patouche I checked https://micrometer.io/ with
- Google Chrome 89.0.4389.90 (Official Build) (x86_64)
- Firefox 87.0 (64-bit)
- Safari Version 14.0.3 (16610.4.3.1.7)

I'm on mac and it worked with all of these browsers. I got an error registering a service worker but I don't see the error you got. I also think `p<l.length;` is totally valid javascript so browsers should be able to parse it correctly.

Could you please try it with the latest Firefox (87.0)? Can this caused by one of your extensions? Could you please try in incognito/private mode?
Also, what is your OS you tried this?

**Comment by Patouche** [comment]
Hello,

I'm using an Ubuntu 20.04 (for work). On my personal macbook, I didn't have this error.

When I tried with all plugins disabled, its working fine. I will try to identify the plugin which cause this issue but clearly, it's not on your side :wink: !

Sorry for this issue.

**Comment by jonatan-ivanov** [comment]
@Patouche If you find it, would you please comment on this issue so that other people who bump into this will know the cause.
