### ISSUE TITLE
Broken site: https://micrometer.io/docs/guide/healthAsGauge

### ISSUE THREAD

**Issue by pgpbpadilla** [micrometer-metrics/micrometer-docs#159]
## Expected

Not a blank page

## Actual 

A blank page

## System configuration 

Tested on: 

- OS: MacOS
- Browser: Chrome, Safari and Firefox

### Browser Network tools

```
# Request

GET /docs/guide/healthAsGauge HTTP/1.1
Host: micrometer.io
sec-ch-ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36

# Response Preview
You need to enable JavaScript to run this app.
```

**Comment by pgpbpadilla** [comment]
Thanks! A 404 would be appropriate in that case. Just a suggestion ;)

**Comment by shakuzen** [comment]
> Thanks! A 404 would be appropriate in that case. Just a suggestion ;)

I opened #180 to follow up on that
