### ISSUE TITLE
Document @Counted

### ISSUE THREAD

**Issue by dbnex14** [micrometer-metrics/micrometer-docs#170]
I find that the documentation of micrometer is quite poor.  E.g while Timed is documentad OK, Counted is not at all

**Comment by dbnex14** [comment]
I cannot help you if I have no good understand of how it works.  And I have no good understanding of how it works as I am not able to find good documentation.

**Comment by jonatan-ivanov** [comment]
Closing in favor of https://github.com/micrometer-metrics/micrometer-docs/issues/172
