### ISSUE TITLE
Update support page for 1.8 release

### ISSUE THREAD

**Issue by nikobearrr** [micrometer-metrics/micrometer-docs#192]
**Please describe the feature request.**
Micrometer support policy should include releases 1.7 and 1.8

**Rationale**
Opening the docs here: https://micrometer.io/docs/support does not say anything about 1.7 (latest) and 1.8 (beta)
As a user I'd like to be able to know whether or not they will be LTS or not.

**Comment by shakuzen** [comment]
Perhaps you are receiving a cached, old version of the website. We made some changes a little while ago with https://github.com/micrometer-metrics/micrometer-docs/issues/174 to try to remove this caching so the latest version of the site is always served. Could you try loading the website with caching disabled (e.g. do a hard refresh in your browser) and let us know if you get a different result? Information about 1.7 has been updated on the support page for a long time now.

We don't have information about 1.8 on there yet, but the plan is for it to be the next LTS release. I'll use this issue to add that information in some form.

**Comment by nikobearrr** [comment]
Hi, I just opened it from my phone and you are correct. It seems as if I had a cached version

**Comment by shakuzen** [comment]
Thank you for checking that. Sorry about the trouble with the cached version. We think it is fixed going forward, but if your browser has a cached version from before we made the fix, it may continue using that version, unfortunately.

**Comment by jonatan-ivanov** [comment]
@nikobearrr Could you please check if hard refresh resolved the isse?
If not, could you please check if clearing all site data in dev mode helps (please make sure you check the unregister service workers option too)?

**Comment by shakuzen** [comment]
@nikobearrr I've updated the support documentation to mention the release cadence of LTS releases now, so this should help in any planning for users of Micrometer. I've also updated the [Micrometer milestones](https://github.com/micrometer-metrics/micrometer/milestones) to mention the intention for 1.8 to be an LTS release.

**Comment by nikobearrr** [comment]
Hi @jonatan-ivanov after a hard refresh (cmd+shift+R) I can see the updated page

**Comment by shakuzen** [comment]
I've also opened #193 to consider removing the concept of non-LTS versions since I'm no longer sure when we would do such a release anymore.
