### ISSUE TITLE
Examples on sending histogram and Distribution metrics to Datadog

### ISSUE THREAD

**Issue by sutekar** [micrometer-metrics/micrometer-docs#195]
Following this document - https://micrometer.io/docs/concepts#_histograms_and_percentiles to send histogram and distribution metrics to Datadog using Micrometer library. No percentile metrics are coming in case of Histogram and no distribution metrics are coming.

Here is sample code I have added into springboot application:
```java
	@PostMapping(value = "testEndpoint/")
	@ResponseBody
	public  ResponseEntity<String> sendEmployeeDataToConsumer() throws RestClientException, IOException{
// To send distribution summary metric
		DistributionSummary summary = DistributionSummary
			    .builder("response.size")
			    .description("Test distribution metric")
			    .baseUnit("bytes")
			    .tags("region", "test")
			    .scale(1000)
			    .register(meterRegistry);
		summary.record(130);
		
// To send histogram metric
		DistributionSummary summary1 = DistributionSummary
		        .builder("http_request_duration_histogram")
		        .tags("region", "test")
		        .serviceLevelObjectives(50, 75, 90, 95)
		        .publishPercentileHistogram()
		        .register(meterRegistry);
		summary1.record(400);
		   
		return ResponseEntity.accepted().body("Hello World");
	}
```
Is there anything missing in above snippet to send Histogram and distribution summary metric to Datadog?

**Comment by shakuzen** [comment]
>     1. Sending histogram and distribution type metrics both not possible with API approach ?

According to [Datadog's document](https://docs.datadoghq.com/metrics/types/?tab=histogram#submission), it is not possible to submit a histogram type with the HTTP API. However, there is no histogram type in the Datadog backend, anyways. Histograms get converted to several gauges, as explained on the same page. We send the count, max, avg, and sum for Timer and DistributionSummary types, which is close to what is sent via DogStatsD histograms.

We added support for Datadog distribution type metrics in https://github.com/micrometer-metrics/micrometer/issues/1056. I will update our documentation accordingly.

**Comment by hdv** [comment]
@shakuzen do you have an issue that tracks documentation part? 
I'd like to know when there's some progress in that area.

**Comment by jonatan-ivanov** [comment]
@hdv I think this is the issue that @shakuzen was referring to, here is the fix: https://github.com/micrometer-metrics/micrometer-docs/commit/c34106d033b5f41ebcb501c34076801115b03557

If you don't see this on our site, please try to force reload the page, it might be because of cache issues.

**Comment by shakuzen** [comment]
You can see the latest version of the docs, including the mentioned change, at https://micrometer.io/docs/registry/datadog#_through_dogstatsd_approach
