### ISSUE TITLE
Document Azure integration

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer-docs#196]

**Comment by jonatan-ivanov** [comment]
We had docs for it, they were not linked to the navbar though.
Fixed in https://github.com/micrometer-metrics/micrometer/commit/c9d697dca18da782a042599ca70c1cd84d3a479f
See: https://docs.micrometer.io/micrometer/reference/1.12-SNAPSHOT/implementations/azure-monitor.html
