### ISSUE TITLE
Please provide anchor for all sections

### ISSUE THREAD

**Issue by snicoll** [micrometer-metrics/micrometer-docs#20]
Could you please add anchor for every section? I'd like a direct link to "Hierarchical name mapping" from the JMX section.

**Comment by izeye** [comment]
"Hierarchical name mapping" has an anchor now although I didn't check all sections.

See https://micrometer.io/docs/registry/jmx#_hierarchical_name_mapping

**Comment by snicoll** [comment]
Thank you so much @izeye - I've added links in https://github.com/spring-projects/spring-boot/commit/2002115637e18b30d45701fdba4d002b7620c990

@jkschneider I don't know if that's done for "everything" but my original request is implemented from my perspective (LMK if you want me to rename the description that's a bit too wide).
