### ISSUE TITLE
Upgrade to react-scripts 5.0.0

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer-docs#210]
```
yarn add --exact react-scripts@5.0.0
rm -rf node_modules
yarn install
yarn upgrade
yarn start
```

Seems we're blocked by https://github.com/facebook/create-react-app/issues/11753. Our svg imports that worked before the cra 5.0.0 upgrade are no longer working.

**Comment by azizur** [comment]
Has anyone found a fix/workaround for this issue yet?

**Comment by jonatan-ivanov** [comment]
This is not an issue anymore since we upgraded the site.
