### ISSUE TITLE
Wavefront proxy port is incorrect in wavefront doc

### ISSUE THREAD

**Issue by howardyoo** [micrometer-metrics/micrometer-docs#25]
[http://micrometer.io/docs/registry/wavefront](http://micrometer.io/docs/registry/wavefront)
"The default proxy configuration will push metrics to a Wavefront proxy sitting on localhost:7828."
The default port number 7828 should be 2878. 

Also in section 54.2.12 in [https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-metrics](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-metrics)
the same port number error is observed, and should be changed to 2878.

**Comment by jkschneider** [comment]
Good catch, thanks @howardyoo

**Comment by howardyoo** [comment]
:-) Thanks for the quick response!
