### ISSUE TITLE
Docs: Add a section to describe `uri` property

### ISSUE THREAD

**Issue by r1jsheth** [micrometer-metrics/micrometer-docs#277]
## Scenario

I followed the tutorial from [here](https://github.com/micrometer-metrics/micrometer-docs/blob/main/src/docs/implementations/datadog.adoc)

I wanted to integrate micrometer for my spring boot application. I correctly updated `pom.xml` file and made use of `Autowired` `DatadogMeterRegistry` inside my app. For `DatadogMeterRegistry`, I was using `application.properties` instead of generating `Bean` inside some class.

Here is a snippet of my `application.properties` file

```.properties
management.endpoints.web.exposure.include=metrics
management.metrics.export.datadog.application-key=<correct_key>
management.metrics.export.datadog.api-key=<correct_key>
management.metrics.export.datadog.step=2s
```

## Error

I was getting `403` error repeatedly and wasted **3 hours** to figuring out the issue. 

```log
[datadog-metrics-publisher] ERROR i.m.datadog.DatadogMeterRegistry - failed to send metric metadata to datadog: {"errors":["Forbidden"]}
```

## Solution

The ultimate issue was the `management.metrics.export.datadog.uri` property. It was picking up the default value of `https://api.datadoghq.com`.

While for my datadog account, as it is hosted in region `US5`, the correct value of `management.metrics.export.datadog.uri` should be `https://api.us5.datadoghq.com`.

This was not clear at all, also the error was not descriptive. (As pasted above)

After looking at the [datadog docs](https://docs.datadoghq.com/api/latest/metrics/#get-active-metrics-list), I realized we have to use a region-specific URL.

![image](https://user-images.githubusercontent.com/25662252/211016520-1fd550c5-8807-4b6f-acdc-13a3a7e62457.png)
![image](https://user-images.githubusercontent.com/25662252/211017219-fd5ca5bf-4e08-463b-bcdd-bd28afd4e790.png)

A small section describing how to pick up uri would be of great help and time saving for someone else.

Happy to create a PR on this 😀

**Comment by jonatan-ivanov** [comment]
Sorry to hear it wasted your time. Are region-specific urls a new thing?
Please feel free to open a PR, we might want to notify the Boot team about this too so they can mention it in the Boot docs.

**Comment by shakuzen** [comment]
Sorry this wasn't as clear as it could be. The descriptiveness of the message is partially limited by the response received from Datadog. We could include the URI we are attempting to publish to in the log message, though. Would that have saved time?

**Comment by r1jsheth** [comment]
Thanks, @jonatan-ivanov and @shakuzen for your responses. Definitely having a small line describing how to configure URI property will be beneficial and it will save the time of others as well.
I am busy travelling this week but will be more than happy to open a PR.

**Comment by r1jsheth** [comment]
Hi @jonatan-ivanov and @shakuzen, opened https://github.com/micrometer-metrics/micrometer-docs/pull/285 PR to address this issue. Let me know what you think. Any feedback is welcome. Thanks!
