### ISSUE TITLE
Logo text is sometimes cropped

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer-docs#28]
![image](https://user-images.githubusercontent.com/1697736/38344893-9f55f006-3851-11e8-84b1-83c4cd052239.png)

See https://twitter.com/DJGummikuh/status/981494928181166081

**Comment by DJGummikuh** [comment]
I really need to learn to search for these github projects prior to writing public shaming on Twitter :'D

**Comment by jkschneider** [comment]
No worries :)

**Comment by jonatan-ivanov** [comment]
We upgraded to a new site, this should be fixed.
