### ISSUE TITLE
Update support policy with 1.11.x

### ISSUE THREAD

**Issue by lenin-jaganathan** [micrometer-metrics/micrometer-docs#312]
https://github.com/micrometer-metrics/micrometer-docs/blob/49a30ff85f193f911a76bf7f021c8b96d5508368/src/docs/support/index.adoc?plain=1#L17-L21

Add 1.11.x support to the support policy.

**Comment by lenin-jaganathan** [comment]
Is June release the last one for the 1.9.x chain?

**Comment by shakuzen** [comment]
> Is June release the last one for the 1.9.x chain?

Actually, I think we need to update that. I'll make a separate issue.
