### ISSUE TITLE
Avoid documenting Spring Boot properties in Micrometer documentation for Graphite

### ISSUE THREAD

**Issue by patpatpat123** [micrometer-metrics/micrometer-docs#343]
**Describe the bug**

**Environment**
 - Micrometer version [e.g. 1.7.1] 1.12.0
 - Micrometer registry [e.g. prometheus] **Graphite**
 - OS: [e.g. macOS] reproducible with Linux Mac and Windows
 - Java version: [e.g. output of `java -version`] GraalVM 21

**To Reproduce**
With a SpringBoot 3.2 app, with Actuator and micrometer-registry-graphite in the pom.

Following this doc https://micrometer.io/docs/registry/graphite
I have property ``` management.metrics.export.graphite.host=my-graphite.com:2000```

However, I am always getting 

```
c.c.metrics.graphite.GraphiteReporter    : Unable to report to Graphite
java.net.ConnectException: Connection refused: connec
```
And with the debugger, I see (please see screenshot)

![Screenshot 2023-11-30 214141](https://github.com/micrometer-metrics/micrometer/assets/43899031/e7972488-89c7-406e-8e0b-eda4d3a26b0e)

**Expected behavior**
The property would be taken into account, and not defaulting to localhost

**Comment by izeye** [comment]
I created https://github.com/micrometer-metrics/micrometer-docs/pull/349 to try to resolve this.

**Comment by jonatan-ivanov** [comment]
Closed by https://github.com/micrometer-metrics/micrometer-docs/pull/349
