### ISSUE TITLE
add dynatrace registry docs

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer-docs#48]
_From @pjfanning on July 14, 2018 9:8_

Many registries are documented at https://micrometer.io/docs
Dynatrace support was added in https://github.com/micrometer-metrics/micrometer/issues/272

_Copied from original issue: micrometer-metrics/micrometer#724_

**Comment by pjfanning** [comment]
@shakuzen can you close this - it appears that Dynatrace integration is documented at https://micrometer.io/docs now

**Comment by pjfanning** [comment]
I have a sample project that shows basic dynatrace integration - https://github.com/pjfanning/micrometer-akka-dynatrace
