### ISSUE TITLE
Document Amazon CloudWatch support

### ISSUE THREAD

**Issue by izeye** [micrometer-metrics/micrometer-docs#49]
Amazon CloudWatch support has been added in https://github.com/micrometer-metrics/micrometer/issues/66 but its document hasn't been added yet.

See https://stackoverflow.com/questions/50504949/configuring-springboot-2-application-for-micrometer-for-aws-cloudwatch

**Comment by snicoll** [comment]
Once that's done we need to add a small section in the Spring Boot reference guide as well.

**Comment by holyjak** [comment]
Can I help with this? It would be really nice to get it done.

**Comment by izeye** [comment]
@holyjak Sure, thanks for the offer. A PR would be most welcome.

**Comment by izeye** [comment]
See https://github.com/spring-cloud/spring-cloud-aws/tree/master/spring-cloud-aws-autoconfigure/src/main/java/org/springframework/cloud/aws/autoconfigure/metrics
