### ISSUE TITLE
Consider documenting 3rd party integrations

### ISSUE THREAD

**Issue by izeye** [micrometer-metrics/micrometer-docs#57]
There are a few 3rd party `MeterBinder` supports including [Apache Camel](https://github.com/micrometer-metrics/micrometer/issues/410). It would be nice to have an index page for them like [3rd party Spring Boot starters](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-starters#community-contributions).

**Comment by shakuzen** [comment]
I agree it'd be good if we have a page that links to 3rd party libraries' documentation of their Micrometer metrics.

**Comment by shakuzen** [comment]
I've broadened the scope by making this not just about MeterBinders, but also third-party maintained MeterRegistry implementations or even frameworks. I'd like to prioritize this work so we can highlight good options available in the community outside of the Micrometer repository. I think the challenge lies in the criteria used to determine where we draw the line of what we do not include in the official site.

**Comment by izeye** [comment]
https://github.com/micrometer-metrics/micrometer-docs/pull/326 seems to have resolved this partially.

**Comment by shakuzen** [comment]
Yeah, let's close this and we can consider adding anything missing on a case-by-case basis.

**Comment by izeye** [comment]
@shakuzen Actually, I meant that 3rd party meter registries are still missing with "partially", which you suggested above.

**Comment by shakuzen** [comment]
Do we know of any third-party meter registries other than the apparently now archived New Relic one? https://github.com/newrelic/micrometer-registry-newrelic

**Comment by izeye** [comment]
@shakuzen Ah, no, I didn't check. I just thought that there are some based on your comment above.
