### ISSUE TITLE
Micrometer Abstraction and Implementations

### ISSUE THREAD

**Issue by JanStureNielsen** [micrometer-metrics/micrometer-docs#6]
The [docs](http://micrometer.io/docs) are currently organized as standalone/"one-stop-shop" sections which are specific to an implementation. As you read each of these implementations, you're left with the impression that there's a common abstraction to these but that common abstraction is not described. I was expecting the inverse: a description of the micrometer abstraction with brief notes about how to tie-in  a particular back-end.

The [SLF4J user manual](https://www.slf4j.org/manual.html) takes the abstraction description approach, as does [Apache Commons Logging](https://commons.apache.org/proper/commons-logging/guide.html) with varying degrees of success; [Spring Logging](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html) is probably the most readable from my perspective -- they focus on their abstraction, provide reasonable defaults, and describe how to hook-in specific implementations.

For Micrometer's user manual, I'd prefer to see:

* Quick start
* The Micrometer abstractions
  * Meters
    * Dimentions/Tags
    * Counters
    * Timers
    * Long task timers
    * Gauges
    * Distribution summaries
  * Meter registry
    * Global registry
    * Composite registries
    * Spectator-backed...
* Binders
  * JVM and system monitoring
  * Cache monitoring
  * `Executor` and `ExecutorService` monitoring
  * Logback monitoring
* Spring Support
  * Configuring
  * Web monitoring
  * Scheduling
  * Data source monitoring
* Back-end implementations
  * Atlas
  * Promethues
  * Datadog
  * Influx
  * Gaphite
  * Ganglia
  * JMX

**Comment by jkschneider** [comment]
Hopefully the restructured docs make more sense.
