### ISSUE TITLE
Document KairosDB integration

### ISSUE THREAD

**Issue by snicoll** [micrometer-metrics/micrometer-docs#68]
KairosDB integration was implemented in https://github.com/micrometer-metrics/micrometer/issues/761 and auto-configured in Spring Boot 2 in https://github.com/spring-projects/spring-boot/issues/14821

The snapshot of the Spring Boot guide has a link to http://micrometer.io/docs/registry/kairos that's not available yet.

**Comment by izeye** [comment]
KairosDB documentation seems to be available now with the link.
