### ISSUE TITLE
Better document Datadog host tag semantics

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer-docs#70]

**Comment by randysecrist** [comment]
If you have a repo / place for where you want this documentation to go; I'll give you some free labor and do some editing and submit a PR.

**Comment by jkschneider** [comment]
@randysecrist Thanks. Also, probably in the Datadog implementation doc: https://github.com/micrometer-metrics/micrometer-docs/blob/master/src/docs/implementations/datadog.adoc

**Comment by izeye** [comment]
I created https://github.com/micrometer-metrics/micrometer-docs/pull/139 to try to resolve this.
