### ISSUE TITLE
Document Stackdriver support

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer-docs#77]

**Comment by saturnism** [comment]
hiya! thnx for merging this. i thought the info was showing up on the site, but not anymore?
https://micrometer.io/docs

Stackdriver is still missing from the list for some reason.

**Comment by shakuzen** [comment]
> Stackdriver is still missing from the list for some reason.

It's probably a caching issue. I'm able to see it, for what it's worth. Can you try forcing the browser  to refresh (not use the cache)?

**Comment by saturnism** [comment]
ah you are right. thnx!
