### ISSUE TITLE
Navigation bar toggler doesn't work

### ISSUE THREAD

**Issue by izeye** [micrometer-metrics/micrometer-docs#88]
IIRC it was working before but I'm not 100% sure.

**Comment by shakuzen** [comment]
Perhaps I didn't realize just how broken this makes the site on mobile view, but it became apparent when @checketts was trying to show me something from his smartphone at SpringOne. I'm no frontend expert, but I'll try to dig into this more soon if no one else who has expertise and interest can help out.

**Comment by izeye** [comment]
@shakuzen I'm not a frontend expert, either, but I confirmed it's been broken since 5aebae878a0ec2c3a421ca5ab248ad792a99e80f. I created #104 which reverts the commit. I confirmed it's working with the change in my local environment.

**Comment by shakuzen** [comment]
I'm seeing this again not on mobile but on chrome on my macbook. It is failing to download the scripts due to a CORS issue. Not sure why exactly, but I've hopefully obviated the whole issue by reimplementing our navbar with react-bootstrap in #181
